import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, { Component } from 'react';
import Pagewhy from 'components/pagewhy';
import Pagehow from 'components/pagehow';
import Pagewhat from 'components/pagewhat';
import PageHero from 'components/pagehero';
import PageHeader from 'components/pageheader';
import PageMember from 'components/pagemember';
import Pagefooter from 'components/pagefooter';
import PageInvestment from 'components/pageinvestment';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='container'>
        <PageHeader></PageHeader>
      </header>

      <div>
        {/* 遠藤さん */}
        <PageHero></PageHero>

        {/* 中島 */}
        <Pagewhy></Pagewhy>
        <Pagewhat></Pagewhat>
        <Pagehow></Pagehow>

        {/* 浅井さん */}

        <PageMember></PageMember>
        {/* <PageInvestment></PageInvestment> */}
      </div>

      <footer className={styles.footer}>
        <Pagefooter></Pagefooter>
      </footer>
    </div>
  );
}
